### ISSUE TITLE
Request file-in support for Pharo files

### ISSUE THREAD

**Issue by feldti** [jgfoster/Jade#56]
If I paste source code into a workspace, slect it all and the filein just gives me a strange dialog and nothing is happening
[PMAccuracy.txt](https://github.com/jgfoster/Jade/files/7340361/PMAccuracy.txt)
.

**Comment by jgfoster** [comment]
Sorry about that. It turns out that the import works for Topaz format (and maybe VW?), but not for Pharo. I'll edit this into a request for Pharo support but honestly it will be a low priority (unless the work is sponsored!). My advice is to use Monticello to export from Pharo and load into GemStone.

**Comment by feldti** [comment]
Well, that would be the better way ... but looking at Pharo 9.0 I was not able to find that option anyway.

**Comment by jgfoster** [comment]
I do have a file-out from Pharo that I'd like to load into GemStone, so the chance of me at least investigating this is a bit higher than it was!

**Comment by jgfoster** [comment]
I've chosen to do this as a file-to-file translation since it is faster to load via Topaz and it is easier to catch and fix errors. See the new menu command on Transcript->File. Please reopen this with comments if you have issues or suggestions.
