### ISSUE TITLE
Add vcruntime140.dll to bin directory

### ISSUE THREAD

**Issue by feldti** [jgfoster/Jade#74]
When I try to connect to a Gemtone/S 3.7.0 database Jade tries to load the corresponding 3.7.0 libraries and an error dialog pops up  and tells me, that its not a valid application.

![jade-gemstone370](https://github.com/jgfoster/Jade/assets/24528907/b1996cc4-9aac-4b42-9f98-369f33eaa979)

**Comment by feldti** [comment]
Its simple to fix this: just add vcruntime140.dll to your jade bin directory - you may get this file (and others) from the GemtalkSystems Window Client library archive free downloadable from their web site.

**Comment by jgfoster** [comment]
We currently provide msvcr90.dll, msvcr100.dll, msvcr110.dll, msvcr120.dll and @feldti reports that vcruntime140.dll is needed (maybe this works for me because I already had it installed). I'd like to figure out the relationship between that file and msvcr140.dll and msvcp140.dll (at one time there was a _debug_ library that was not supposed to be redistributed).
