### ISSUE TITLE
Jade 2.4.26 - Login List resetted ...

### ISSUE THREAD

**Issue by feldti** [jgfoster/Jade#77]
This still happens for (yesterday quite often) - then all connections and login informations are gone and the list is set to one default entry.

My new hint here is, that I switched yesterday very often between different GS versions and had wrong connection data entered

**Comment by jgfoster** [comment]
What version of Jade is this? Did Jade crash and leave the data cleared when you restarted?

The existing code [`JadeLoginShell>>saveDataTo:](https://github.com/jgfoster/Jade/blob/main/sources/JadeLoginShell.cls) makes quite an effort to avoid data loss (writing to a temp file, then deleting the existing file and renaming the temp file). You might look for the data (mine is at C:\Users\jfoster\AppData\Roaming\JadeData.gss) and make a copy of it for backup.


![Screenshot 2023-12-28 at 8 34 46 PM](https://github.com/jgfoster/Jade/assets/1577872/ab0fb4e9-2ce6-429e-9284-f00b96cfd6c6)

**Comment by feldti** [comment]
Long time, but now it seems, that on my machine I can do the following and then the list is lost:

Start Jade - you get the login window
Define a source, Do a Login, you get a browser
close the login window
close the browser window

Start jade, list is lost

if you close the browser window before the login window, the list is NOT lost

**Comment by jgfoster** [comment]
The steps to repeat were very helpful. It turns out that we keep the current Transcript window with the login object so you can double-click on the login to get to the Transcript. But if you close the login list with a logged-in session, then it tries to persist the open window. Although that works, we can't recreate the open Transcript window when Jade starts. So since there is an error reading the login list we throw it away and just give a default list. The solution is to clear the session/transcript from the login object that is written to disk so that when we reopen Jade it does not try to recreate the session and transcript.
